### ISSUE TITLE
Switch the language?

### ISSUE THREAD

**Issue by descof2** [bgraver/lolesports-graphics#1]
Hello Brandon Graver,

I am writing to request a language change of this lolesports-graphics project from Python to a more sophisticated language for big chads. I understand that with Python it is much simpler and easier to create graphs from raw data, but you are no longer a child and it's time to adopt a big boy language like MatLab. 

Thanks,
Darell E.

**Comment by mckernant1** [comment]
I would like to reemphasize the point made by Darell E. and also assert that python is for soyboys

**Comment by bgraver** [comment]
All of these bot creators are actually just bot accounts, wow.
